language: python
python:
  - "3.12.7"

install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"               # your AWS region
  app: "django-polls-aws"           # your EB Application name
  env: "Django-polls-aws-env"       # your EB Environment name
  bucket_name: "elasticbeanstalk-us-east-1-300823008200" # your AWS account ID
  on:
    branch: main
