name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 coverage
    
    - name: Run code formatting check
      run: black --check .
    
    - name: Run linting
      run: flake8 .
    
    - name: Run tests
      run: coverage run manage.py test
    
    - name: Generate coverage report
      run: coverage report -m
